// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SmartParking
{
    public partial class ViewController : NSViewController
	{
		public ViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Do any additional setup after loading the view.

            Admin.getPasswords();
            
        }

        public override NSObject RepresentedObject
        {
            get
            {
                return base.RepresentedObject;
            }
            set
            {
                base.RepresentedObject = value;
                // Update the view, if already loaded.
            }
        }

        User Admin = new User();


        partial void OnClickLoginButton(Foundation.NSObject sender)
		{
            
			if(Admin.Username == LoginNameEntry.StringValue && Admin.Password == PaswordEntry.StringValue)
            {
                this.View.Window.Close();
                PerformSegue("Transition", sender); //open next window
            }
            else
            {
                WrongEntry.Hidden = false;
            }
		}
    }
}
